name: Generate and Slice Stats Image

on:
workflow_dispatch:
push:
paths:
- 'scripts/**'
- 'data/**'
- '.github/workflows/generate.yml'

jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout repo
uses: actions/checkout@v3

- name: Setup Node.js
uses: actions/setup-node@v3
with:
node-version: 20

- name: Install canvas dependencies
run: |
sudo apt-get update
sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev

- name: Install dependencies
run: npm install

- name: Generate tall images
run: npm run generate

- name: Split images into items
run: npm run split

- name: Commit changes
run: |
git config --global user.name 'github-actions'
git config --global user.email 'github-actions@github.com'
git add .
git commit -m "Auto update stats image and slices" || echo "No changes to commit"
git push
