name: Split babyother 001 Images

on:
  workflow_dispatch:

  schedule:
    # هر روز ساعت 08:00 به وقت ترکیه (05:00 UTC)
    - cron: '0 5 * * *'

  push:
    paths:
      - 'daily/baby/babyother/bao-001.png'
      - 'scripts/baby/bao-001s.mjs'
      - '.github/workflows/baby-bao-001s.yml'

permissions:
  contents: write

jobs:
  split-baby-bao-001s-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install canvas dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libcairo2-dev \
            libpango1.0-dev \
            libjpeg-dev \
            libgif-dev \
            librsvg2-dev

      - name: Install npm packages
        run: npm install

      - name: Run bao-001s splitter script
        run: node scripts/baby/bao-001s.mjs

      - name: Commit and push bao-001s sliced images
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull --rebase origin main
          git add daily/baby/babyother/sliced/ || echo "No sliced images to add"
          git commit -m "Auto-split: updated sliced images from bao-001.png" || echo "No changes to commit"
          git push origin HEAD:main
