name: Split Images

on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/splitter.mjs'
      - 'daily/clothing/women/001.png'
      - '.github/workflows/split.yml'

jobs:
  split-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install canvas dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Install dependencies
        run: npm install

      - name: Run splitter script
        run: node scripts/splitter.mjs

      - name: Commit results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add daily/clothing/women/sliced/
          git commit -m "Auto split updated 001.png" || echo "No changes to commit"
          git push
